/** Official PNMC recognition checklist (Regulations 2023) */
export const OFFICIAL_CHECKLIST_ITEMS = [
  {
    number: 1,
    flag: 'Flag – B',
    category: 'General Requirements',
    title:
      'Completely filled in the Application Form and Institution Cover Letter.',
    provision: 'Section 12(1) Regulation 3(1) &36 – Page No. 67',
    regulationRef: 'Section 12(1) Regulation 3(1) &36 – Page No. 67',
    hasFeeDetails: false,
  },
  {
    number: 2,
    flag: 'Flag – C',
    category: 'General Requirements',
    title:
      'Certified Copy of Business/Trade Name regarding Registration of Name under the Trade Mark Ordinance, 2001 (Ordinance No XIX of 2001)',
    provision: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 3,
    flag: 'Flag – D',
    category: 'General Requirements',
    title:
      'Certified copy of the Certificate of Incorporation with Memorandum of Association and Articles of Association from SECP, or Partnership Firm Registration Certificate with Partnership Deed.',
    provision: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 4,
    flag: 'Flag – E',
    category: 'General Requirements',
    title:
      'Income Tax Return of the CEO/Directors or Managing Partner/Partners, or Owners, as proof of financial capacity to run and manage the affairs of the educational institution.',
    provision: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 5,
    flag: 'Flag – F',
    category: 'General Requirements',
    title:
      'Availability of funds to meet the requirements of the next five years in the Account of the Institution, supported by the Bank Statement',
    provision: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 6,
    flag: 'Flag – G',
    category: 'General Requirements',
    title: 'Certified Copy or Original NOC from the relevant Municipal Authority.',
    provision: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a) Regulation3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 7,
    flag: 'Flag – H',
    category: 'General Requirements',
    title:
      'Certified Copy or Original Affiliation Agreement with Hospital for Clinical Training of Students.',
    provision: 'Regulation 8(1) & 36 - Page No. 07 & 18',
    regulationRef: 'Regulation 8(1) & 36 - Page No. 07 & 18',
    hasFeeDetails: false,
  },
  {
    number: 8,
    flag: 'Flag – I',
    category: 'General Requirements',
    title:
      'Details regarding the Existing Affiliation Agreement with Hospitals for the clinical Training of students, including facilities.',
    provision: 'Regulation 8 (2) & 36- Page No. 07 & 18',
    regulationRef: 'Regulation 8 (2) & 36- Page No. 07 & 18',
    hasFeeDetails: false,
  },
  {
    number: 9,
    flag: 'Flag – J',
    category: 'General Requirements',
    title:
      'Fee Payment: Fee payment Receipt/Challan Habib Metropolitan Bank Ltd. Account No. (PK44MPBL9737477140108727). Attach the original Fee Challan.',
    provision: 'Regulation 58 – Page No. 26',
    regulationRef: 'Regulation 58 – Page No. 26',
    hasFeeDetails: true,
  },
  {
    number: 10,
    flag: 'Flag – K',
    category: 'General Requirements',
    title:
      'Affidavit duly attested to the facts and documents annexed to the Application Form.',
    provision: 'Regulation 3(3) & 4 - Page No. 05',
    regulationRef: 'Regulation 3(3) & 4 - Page No. 05',
    hasFeeDetails: false,
  },
  {
    number: 11,
    flag: 'Flag – L',
    category: 'Faculty Details and Requirements',
    title:
      'Proof of Faculty Members, including names, educational qualifications, names of educational institutions from which educational qualifications were acquired, with authentication or verification status, address, name, and place of employer organization.',
    provision: 'Regulation 7(1) & 36 - Page No. 06 & 18',
    regulationRef: 'Regulation 7(1) & 36 - Page No. 06 & 18',
    hasFeeDetails: false,
  },
  {
    number: 12,
    flag: 'Flag – M',
    category: 'Faculty Details and Requirements',
    title: 'Details of existing faculty members.',
    provision: 'Regulation 7(2) & 36 - Page No. 06 & 18',
    regulationRef: 'Regulation 7(2) & 36 - Page No. 06 & 18',
    hasFeeDetails: false,
  },
  {
    number: 13,
    flag: 'Flag – N',
    category: 'Faculty Details and Requirements',
    title:
      'Details regarding Service Contracts with faculty members, with details of their Remuneration.',
    provision: 'Regulation 7(2) & 36 - Page No. 06 & 18',
    regulationRef: 'Regulation 7(2) & 36 - Page No. 06 & 18',
    hasFeeDetails: false,
  },
  {
    number: 14,
    flag: 'Flag – O',
    category: 'Proper Infrastructure (Building) Requirement',
    title: 'Duly attested or certified Map of Building (Full Size).',
    provision: 'Section 12(2)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section 12(2)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 15,
    flag: 'Flag – P',
    category: 'Proper Infrastructure (Building) Requirement',
    title:
      'Permission from relevant authorities for Business and Commercial use of the building.',
    provision: 'Section12(2)(a)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 16,
    flag: 'Flag – Q',
    category: 'Proper Infrastructure (Building) Requirement',
    title:
      'Whether Class Rooms properly constructed with the capacity to accommodate a class and have attached pictures.',
    provision: 'Section12(2)(a)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 17,
    flag: 'Flag – R',
    category: 'Proper Infrastructure (Building) Requirement',
    title: 'Durability Certificate of the Building.',
    provision: 'Section12(2)(a)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 18,
    flag: 'Flag – S',
    category: 'Proper Infrastructure (Building) Requirement',
    title: 'Administrative Infrastructure.',
    provision: 'Section12(2)(a)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    regulationRef: 'Section12(2)(a)(b)(i) Regulation 3(2)&36- Page No. 05 & 18',
    hasFeeDetails: false,
  },
  {
    number: 19,
    flag: 'Flag – T',
    category: 'Proper Infrastructure (Building) Requirement',
    title: 'Installation of CCTV Cameras and Attached Pictures.',
    provision: 'Regulation 55 & 56 - Page No. 25',
    regulationRef: 'Regulation 55 & 56 - Page No. 25',
    hasFeeDetails: false,
  },
  {
    number: 20,
    flag: 'Flag – U',
    category: 'Details and requirements regarding clinical facilities',
    title:
      'Details of the Hospital Providing Clinical Facilities and Beds Statement',
    provision: 'Section12(2)(a)(b) (iii) Regulation 3(2)- Page No. 05',
    regulationRef: 'Section12(2)(a)(b) (iii) Regulation 3(2)- Page No. 05',
    hasFeeDetails: false,
  },
  {
    number: 21,
    flag: 'Flag – V',
    category: 'Details and requirements regarding clinical facilities',
    title:
      "Certified Copies of the Memorandum of Understanding (MOU) for the provision of Clinical facilities for the Applicant's educational Institutions.",
    provision: 'Section12(2)(a)(b) (iii) Regulation 3(2)- Page No. 05',
    regulationRef: 'Section12(2)(a)(b) (iii) Regulation 3(2)- Page No. 05',
    hasFeeDetails: false,
  },
  {
    number: 22,
    flag: 'Flag – W',
    category: 'Details and requirements regarding clinical facilities',
    title:
      'Certified Copies of the Memorandum of Understanding (MOU) for the provision of Clinical Facilities to the other educational Institutions.',
    provision: 'Section 12(2)(a)(b) (iii) Regulation 3(2)- Page No. 05',
    regulationRef: 'Section 12(2)(a)(b) (iii) Regulation 3(2)- Page No. 05',
    hasFeeDetails: false,
  },
  {
    number: 23,
    flag: 'Flag – X',
    category: 'Details and requirements regarding clinical facilities',
    title:
      'Registered or Declared by Documentary proof from the Affiliating Hospital regarding the sanctioned capacity of the Hospital.',
    provision: 'Section 12(2)(a)(b) (iii) Regulation 3(2)- Page No. 05',
    regulationRef: 'Section 12(2)(a)(b) (iii) Regulation 3(2)- Page No. 05',
    hasFeeDetails: false,
  },
] as const;

export const DEFAULT_FEE_LINE_ITEMS = [
  { code: 'MSN', label: 'MSN', amount: 200000, remainingFee: null, selected: false },
  { code: 'BSN', label: 'BSN', amount: 200000, remainingFee: null, selected: false },
  { code: 'PRN', label: 'PRN', amount: 200000, remainingFee: null, selected: false },
  { code: 'LHV', label: 'LHV', amount: 100000, remainingFee: null, selected: false },
  { code: 'CMW', label: 'CMW', amount: 100000, remainingFee: null, selected: false },
  { code: 'CNA', label: 'CNA', amount: 100000, remainingFee: null, selected: false },
  { code: 'OTHER_DEGREE', label: 'Other Degree', amount: 200000, remainingFee: null, selected: false },
  { code: 'OTHER_DIPLOMA', label: 'Other Diploma', amount: null, remainingFee: null, selected: false },
  { code: 'EVENING_SHIFT', label: 'Evening Shift', amount: null, remainingFee: null, selected: false },
  { code: 'ENHANCEMENT', label: 'Enhancement', amount: 300000, remainingFee: null, selected: false },
  { code: 'INSPECTION_FEE', label: 'Inspection Fee', amount: 250000, remainingFee: null, selected: false },
  { code: 'APPLICATION_FEE', label: 'Application Fee', amount: 50000, remainingFee: null, selected: false },
];
